### ISSUE TITLE
Cryptography Deprecation

### ISSUE THREAD

**Issue by mglt** [mglt/draft-mglt-dnsop-dnssec-validator-requirements#5]
This section needs to be clarified. In particular it seems unclear that signature scheme are retrieved by requesting a DNSKEY.

envisioned action points: 
1) clarify the text and mentioning how the signature schemes are discovered.
2) It is unclear if we should keep track of the requested domain, in order to be able to request the DNSKEYs 
3) emphasize on a communication of supported algorithms between authoritative servers and resolvers.

**Comment by bortzmeyer** [comment]
No. This is not how DNSSEC works. 3) is wrong because there is no such thing as "supported algorithms in the authoritative server" (except for online signing). Algorithms are choosen by the zone master, and are recorded in the DNSKEY. There is no way to discuss them dynamically between resolver and authoritative name server.

**Comment by mglt** [comment]
Thanks, what I would have liked to have is a mechanism that enables the validator to advertise the authoritative server signature schemes are out of date.
